live_config_reload = true

import = ["~/.config/alacritty/themes/onedark.toml",]

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
#opacity = 0.7

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 20
y = 20



[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control|Shift"

