

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"


[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control|Shift"

[terminal.shell]
program = "/usr/bin/fish"

[window]
opacity = 0.7

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 20
y = 20

[general]
live_config_reload = true

import = ["~/.config/alacritty/themes/dracula.toml",]
