# Shell variables
# Generated by 'wal'
wallpaper="/home/minhtd/Pictures/wallpaper/dunes-sun.jpg"

# Special
background='#081833'
foreground='#a8b8c2'
cursor='#a8b8c2'

# Colors
color0='#081833'
color1='#9B5377'
color2='#E75B5B'
color3='#145B81'
color4='#375983'
color5='#485783'
color6='#5C7389'
color7='#a8b8c2'
color8='#758087'
color9='#9B5377'
color10='#E75B5B'
color11='#145B81'
color12='#375983'
color13='#485783'
color14='#5C7389'
color15='#a8b8c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
