--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/minhtd/Pictures/wallpaper/dunes-sun.jpg"

-- Special
background="#081833"
foreground="#a8b8c2"
cursor="#a8b8c2"

-- Colors
color0="#081833"
color1="#9B5377"
color2="#E75B5B"
color3="#145B81"
color4="#375983"
color5="#485783"
color6="#5C7389"
color7="#a8b8c2"
color8="#758087"
color9="#9B5377"
color10="#E75B5B"
color11="#145B81"
color12="#375983"
color13="#485783"
color14="#5C7389"
color15="#a8b8c2"
